### ISSUE TITLE
Update terminology to refer to 'sex' rather than 'gender'

### ISSUE THREAD

**Issue by cmrn** [cmrn/slk581#7]
The definition of SLK581 specifies that the key records the sex, rather than gender, of the respondent. Whether this is true in practice is a matter of debate (see below). However, this tool should be based on the official definition rather than how it is used in practice. 

The tool should be updated to consistently refer to this field as "sex" rather than "gender" in the documentation, user interface, source code, and tests.

---

More information about how the ABS considers sex and gender can be found in this article by Ben McGinnes: http://www.adversary.org/wp/2016/07/28/censuspicious/.

While the definitions refer to the field as being a record of the sex of the respondent, their collection methodology indicates that they would in practice use this field to record the gender of the respondent:

> It is usually a simple matter to infer the sex of the respondent through observation, or from other cues such as the relationship of the person(s) accompanying the respondent, or first name. [(source)](http://meteor.aihw.gov.au/content/index.phtml/itemId/349510)

**Comment by Hasimir** [comment]
Yes, it's definitely sex that's the principal concern of the census.  Remember, the full title of the thing is the Census of Population and Housing.  Sex has greater relevance because it relates directly to population growth.  Gender doesn't.

Obviously there will be plenty of claims that that's some form of discrimination, but OTOH the entire issue is moot until such a time as an MtF TW can get pregnant and carry to term.  Personally I doubt such an event will occur in the foreseeable future.
